{% set name = "lume-impact" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: dcabbddd8d9a62491365e459c822c2aeebee3643cdf534d37cf0660cdf5119b4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bokeh
    - distgen
    - numpy
    - openpmd-beamphysics
    - impact-t

test:
  imports:
    - impact

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: LUME Python wrapper Impact-T
  description: |
    LUME Python wrapper Impact-T

extra:
  recipe-maintainers:
    - ChristopherMayes
