{% set name = "lume-impact" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 4f793692e112d35c904c36ad8b97d4121f500fb233cda06f4bfb47eebe9b94fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - bokeh
    - distgen
    - numpy
    - openpmd-beamphysics
    - psutil
    - impact-t
    - lume-base

test:
  imports:
    - impact
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs impact

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: LUME Python wrapper for Impact-T
  description: |
    LUME Python wrapper for Impact-T

extra:
  recipe-maintainers:
    - ChristopherMayes
