{% set name = "lume-impact" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 79a1aef78537e4e02c456e09e5ff1d0a29dabdfc5eb6f9cb7bfa756b60ea70c1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - bokeh
    - distgen
    - numpy
    - openpmd-beamphysics
    - psutil
    - impact-t
    - lume-base

test:
  imports:
    - impact
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs impact

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: LUME Python wrapper for Impact-T
  description: |
    LUME Python wrapper for Impact-T

extra:
  recipe-maintainers:
    - ChristopherMayes
