{% set name = "lume-impact" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f40f4b8b8825ba39f4381dba622e3c811b96061f39d7fcdffd326ebb29390601

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bokeh
    - distgen
    - numpy
    - openpmd-beamphysics
    - impact-t
    - lume-base

test:
  imports:
    - impact  
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs impact    

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: LUME Python wrapper for Impact-T
  description: |
    LUME Python wrapper for Impact-T

extra:
  recipe-maintainers:
    - ChristopherMayes
